# Generated by Django 4.0.6 on 2022-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default='product_image/nodata.png', upload_to='product_image/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('description', models.TextField()),
                ('is_fresh', models.BooleanField(default=True)),
            ],
        ),
    ]
